[package]
name = "googleapis-tonic-google-firestore-v1-1"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.87"
firestore-path = "0.9.26"
google-cloud-auth = { version = "0.17.0", default-features = false, features = ["rustls-tls"] }
google-cloud-token = "0.1.2"
googleapis-tonic-google-firestore-v1 = "0.8.0"
thiserror = "1.0.64"
tokio = { version = "1.40.0", features = ["full"] }
tonic = { version = "0.12.2", default-features = false, features = ["tls-webpki-roots"] }
