[package]
name = "xtask"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.10", features = ["derive"] }
prost-build = "0.13.1"
toml_edit = "0.22.20"
tonic-build = "0.12.1"
