[package]
name = "xtask"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.10", features = ["derive"] }
prost-build = { version = "0.13.1", features = ["cleanup-markdown"] }
semver = "1.0.23"
serde = { version = "1.0.205", features = ["derive"] }
serde_json = "1.0.122"
toml_edit = "0.22.17"
tonic-build = "0.12.1"
