// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FeatureSpec {
    #[prost(string, repeated, tag = "1")]
    pub allowlisted_service_accounts: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
