name: publish
on:
  schedule:
    - cron: "15 15 * * 2"
  workflow_dispatch:
jobs:
  publish:
    concurrency:
      group: publish-job-singleton
      cancel-in-progress: false # default: false
    steps:
      - uses: actions/checkout@v4
      - env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo xtask publish

